apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: webapp
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources: {}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
status: {}